// Where the interface gets its data.
//
// Two implementations behind one shape. Inside Tauri the real graph answers;
// opened as a plain file, a fixture generated by `branchy snapshot` answers
// instead, so the interface can be worked on without building the shell.
//
// Neither one computes anything. Status, tier, the queue and any cycles all
// arrive already worked out by branchy-core, because a second copy of that
// logic in JavaScript is how the two begin to disagree.

(function (global) {
  "use strict";

  function tauriBackend(invoke) {
    return {
      kind: "tauri",
      readOnly: false,
      snapshot: function () {
        return invoke("snapshot");
      },
      execute: function (line) {
        return invoke("execute", { line: line });
      },
      undo: function () {
        return invoke("undo");
      },
    };
  }

  // Answers from the generated fixture. Mutations are refused rather than
  // faked: a half-implemented copy of the engine would be worse than none.
  function fixtureBackend(fixture) {
    return {
      kind: "fixture",
      readOnly: true,
      snapshot: function () {
        return Promise.resolve(JSON.parse(JSON.stringify(fixture)));
      },
      execute: function () {
        return Promise.reject(
          new Error("readonly:This is sample data. Changes need the app itself.")
        );
      },
      undo: function () {
        return Promise.reject(
          new Error("readonly:This is sample data. Changes need the app itself.")
        );
      },
    };
  }

  global.Branchy = global.Branchy || {};
  // `window.__TAURI__` exists only because tauri.conf.json sets
  // `app.withGlobalTauri`. Without it the API is reachable only through an npm
  // import, which would mean a bundler, which this frontend deliberately has
  // no room for.
  global.Branchy.connect = function () {
    var tauri = global.__TAURI__;
    if (tauri && tauri.core && typeof tauri.core.invoke === "function") {
      return tauriBackend(tauri.core.invoke);
    }
    if (tauri && typeof tauri.invoke === "function") {
      return tauriBackend(tauri.invoke);
    }
    return fixtureBackend(global.BRANCHY_FIXTURE || emptySnapshot());
  };

  function emptySnapshot() {
    return {
      areas: [],
      nodes: [],
      queue: [],
      cycles: [],
      tally: { total: 0, done: 0, available: 0 },
    };
  }
})(window);
