// Where the interface gets its data.
//
// Two implementations behind one shape. Inside Tauri the real graph answers;
// opened as a plain file, a fixture generated by `branchy snapshot` answers
// instead, so the interface can be worked on without building the shell.
//
// Neither one computes anything. Status, tier, the queue and any cycles all
// arrive already worked out by branchy-core, because a second copy of that
// logic in JavaScript is how the two begin to disagree.

(function (global) {
  "use strict";

  function tauriBackend(invoke) {
    return {
      kind: "tauri",
      readOnly: false,
      snapshot: function () {
        return invoke("snapshot");
      },
      execute: function (line) {
        return invoke("execute", { line: line });
      },
      executeAll: function (lines) {
        return invoke("execute_all", { lines: lines });
      },
      undo: function () {
        return invoke("undo");
      },

      // Which vaults exist and which is open are the backend's to say. Each
      // of these answers with the whole vault view, so the interface never
      // has to guess what a change did to the list.
      vaults: function () {
        return invoke("vaults");
      },
      createVault: function (name, parent) {
        return invoke("vault_create", { name: name, parent: parent });
      },
      openVault: function (path) {
        return invoke("vault_open", { path: path });
      },
      closeVault: function () {
        return invoke("vault_close");
      },
      forgetVault: function (path) {
        return invoke("vault_forget", { path: path });
      },
      setOpenLast: function (on) {
        return invoke("vault_open_last", { on: on });
      },
      // resolves to a folder, or to null if the person cancelled
      pickFolder: function (title) {
        return invoke("pick_folder", { title: title });
      },
    };
  }

  // Answers from the generated fixture. Mutations are refused rather than
  // faked: a half-implemented copy of the engine would be worse than none.
  //
  // The sample is presented as one vault that can be closed and reopened, so
  // the vault screen can be worked on in a browser too. Creating, forgetting
  // and picking folders need the real thing.
  function fixtureBackend(fixture) {
    var sample = { name: "Sample", path: "ui/dev-fixture.js", missing: false };
    var open = true;
    function view() {
      return Promise.resolve({
        open: open ? sample : null,
        recent: [sample],
        open_last: false,
        pinned: false,
      });
    }
    return {
      kind: "fixture",
      readOnly: true,
      snapshot: function () {
        return Promise.resolve(JSON.parse(JSON.stringify(fixture)));
      },
      execute: refuse,
      executeAll: refuse,
      undo: refuse,
      vaults: view,
      openVault: function () {
        open = true;
        return view();
      },
      closeVault: function () {
        open = false;
        return view();
      },
      createVault: refuse,
      forgetVault: refuse,
      setOpenLast: refuse,
      pickFolder: refuse,
    };
  }

  function refuse() {
    return Promise.reject(
      new Error("readonly:This is sample data. Changes need the app itself.")
    );
  }

  global.Branchy = global.Branchy || {};
  // `window.__TAURI__` exists only because tauri.conf.json sets
  // `app.withGlobalTauri`. Without it the API is reachable only through an npm
  // import, which would mean a bundler, which this frontend deliberately has
  // no room for.
  global.Branchy.connect = function () {
    var tauri = global.__TAURI__;
    if (tauri && tauri.core && typeof tauri.core.invoke === "function") {
      return tauriBackend(tauri.core.invoke);
    }
    if (tauri && typeof tauri.invoke === "function") {
      return tauriBackend(tauri.invoke);
    }
    return fixtureBackend(global.BRANCHY_FIXTURE || emptySnapshot());
  };

  function emptySnapshot() {
    return {
      areas: [],
      nodes: [],
      queue: [],
      cycles: [],
      tally: { total: 0, done: 0, available: 0 },
    };
  }
})(window);
